name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret Value
      env:
        SUPER_SECRET: ${{ secrets.ACR_DEV_USERNAME }}
      run: |
        echo "The value of SUPER_SECRET is: $SUPER_SECRET"
    
    # Add other steps for your CI/CD workflow here
